### ISSUE TITLE
DNS lookup goes wrong for some domains when there is no _radiotag SRV record

### ISSUE THREAD

**Issue by UlrikBrinck** [nickpiggott/odr-radiodns-bridge#4]
If a domain has _radioepg._tcp and _radiovis._tcp SRV records, but no _radiotag._tcp SRV record, some name servers return NOERROR instead of NXDOMAIN, when lookup of _radiotag._tcp.domain.tld is tried. This seems to trigger, that odr-radioepg-bridge does not add information from that domain to the EPG.

It's observered with the domain kanalplus.fm.

Workaround for now is to remove or comment-out line 13 "('radiotag', 'TCP')," in pyradiodns/rdns.py.

**Comment by UlrikBrinck** [comment]
Services using the domain kanalplus.fm, taken from the services section of mux.conf:

    srv-retro {
        id 0x9102
        label "Retro-Radio"
        shortlabel "Retro"
        pty 27
    }

    srv-rockkanalen {
        id 0x9103
        label "Rockkanalen"
        shortlabel "Rockkanl"
        pty 11
    }

    srv-millennium {
        id 0x910b
        label "Retro Millennium"
        shortlabel "RetroMil"
        pty 10
    }

**Comment by nickpiggott** [comment]
This is an issue raised by pyradiodns, so I'll raise it as an issue on that package.
